name: personal-mono-repo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # - pandas
  # - openpyxl
  # - requests
  # - beautifulsoup4
  # - pip:
  #     - dbt-sqlite
  #     - yfinance
  #     - yt-dlp
